services:
  simple-gpu-alert:
    image: quentinmaisonneuve/simplegpualert:${project.version}-arm64v8
    volumes:
      - {local_path_to_configuration.properties}:/app/simple-gpu-alert/configuration.properties
      - {local_path_to_log_folder}:/app/simple-gpu-alert/log
    restart: always